api_version: 1
runtime: python
threadsafe: true
env: flex
entrypoint: gunicorn -b :$PORT fetcher:app

runtime_config:
  python_version: 3

handlers:
# The root URL (/) is handled by the WSGI application named
# "app" in home.py. No other URLs match this pattern.
- url: /
  script: fetcher.app
